from sympy import latex,sympify

def make_subs_dict(mod,vars_only = True):
    """Returns a dictionary of sympy formatted strings
    for the fluxes, control and elasticity 
    coefficients for a model 'mod'. Eg:

    For a model with 
    reactions:
    v_1, v_2
    species:
    S, x_1, P
    the dictionary will look like:

    {'J_v_1'      : 'J_v1',
     'J_v_2'      : 'J_v2',
     'ec_v_1_S'   : 'varepsilon__v1_S',
     'ec_v_1_x_1' : 'varepsilon__v1_x1',
     'ec_v_2_x_1' : 'varepsilon__v2_x1',
     'ec_v_2_P'   : 'varepsilon__v1_P',
     'ccJ_v_1_v_1': 'C__Jv1_v1',
     'ccJ_v_1_v_2': 'C__Jv1_v2',
     'ccJ_v_2_v_1': 'C__Jv2_v1',
     'ccJ_v_2_v_2': 'C__Jv2_v2',
     'ccJ_S_v_1'  : 'C__S_v1',
     'ccJ_S_v_2'  : 'C__S_v2',
     'ccJ_x_1_v_1': 'C__x1_v1',
     'ccJ_x_1_v_2': 'C__x1_v2',
     'ccJ_P_v_1': 'C__P_v1',
     'ccJ_P_v_2': 'C__P_v2'}

    }

    Used in conjunction with expression to latex, but
    might be useful on its own. 

    Arguments:
    ==========
    mod       - The model object
    vars_only - If 'False' elasticity coefficient expression for model 
                parameters are included (optional - default='True')
    """
    ec_subs = {}
    j_subs = {}
    cc_subs = {}

    for reaction in mod.reactions:
        j_subs['J' + reaction] = 'J_' + reaction.replace('_','')
        
        for species in mod.species:
            ec_orig_expr = ('ec' +
                            reaction + 
                            '_' + 
                            species
            )
            ec_new_expr = ('varepsilon__' +  
                           reaction.replace('_','') + 
                           '_' + 
                           species.replace('_','')
            )  

            ec_subs[ec_orig_expr] = ec_new_expr 

        for each in mod.reactions:
            cc_orig_expr = ('ccJ' + 
                            reaction +
                            '_' +
                            each
            )
            cc_new_expr = ('C__J' + 
                           reaction.replace('_','') + 
                           '_' + 
                           each.replace('_','')
            )

            cc_subs[cc_orig_expr] = cc_new_expr

    for species in mod.species: 
        for reaction in mod.reactions:
            cc_orig_expr = ('cc' +
                            species + 
                            '_' + 
                            reaction
            )
            cc_new_expr = ('C__' +
                           species.replace('_','') + 
                           '_' +
                           reaction.replace('_','')
            )
            
            cc_subs[cc_orig_expr] = cc_new_expr

    if vars_only == False:
        for reaction in mod.reactions:
            for param in mod.parameters:
                ec_orig_expr = ('ec' +
                            reaction + 
                            '_' + 
                            param
                )
                ec_new_expr = ('varepsilon__' +  
                               reaction.replace('_','') + 
                               '_' + 
                               param.replace('_','')
                )  

                ec_subs[ec_orig_expr] = ec_new_expr

    subs = {}
    subs.update(ec_subs)
    subs.update(cc_subs)
    subs.update(j_subs)

    return subs


def expression_to_latex(subs_dict,expression):
    """Returns a latex expression from a sympy (or string) expression
    using a subtitution dictionary generated by 'make_subs_dict()'
    (or a custom dictionary):

    For subs_dict = {'J_v_2'  : 'J_v2',
                    'ec_v_1_S': 'varepsilon__v1_S'}
    and

    expression = 'J_v_2*ec_v_1_S/10'

    the output will be:

    '\\frac{J_{v2}\\varepsilon^{v1}_{S}}{10}'

    Arguments:
    ==========
    subs_dict  - The substitution dictionart
    expression - The sympy or string dictionary
    """
    if type(expression) == str:
        expr = sympify(expression)
    else:
        expr = expression

    latex_expr = latex(expr.subs(subs_dict),long_frac_ratio = 10)

    return latex_expr